### ISSUE TITLE
more than 2 conditions?

### ISSUE THREAD

**Issue by ckastall** [petitmingchang/TO-GCN#1]
Would it be possible to compare more than 2 conditions using this pipeline?

**Comment by petitmingchang** [comment]
This method can be applied to more than two conditions for sure. However, we only implement 2 conditions in this version. I will try to compare more conditions in the next update. Thanks for your comment!

**Comment by ckastall** [comment]
Thank you for your answer.

In my case I have 2 conditions (in addition to time), with two possible states for each. Would it be possible to still use the present version by running the pipeline for each comparison pair (ie 4 comparisons)? Would you have specific suggestions for such an approach?

**Comment by petitmingchang** [comment]
Ha! It is not an easy mission to do four comparisons using this version.
I think you can use GCN to do six time pair-wise comparisons for four conditions or states. Then collect them and pick out the combinations of gene coexpression relationships you want by yourself.

**Comment by ckastall** [comment]
Thank you for the feedback!
I'll try to make some tests and come back to you if I have further questions, I guess I can close this now.
