### ISSUE TITLE
How to run the Single_Time-series_data program?

### ISSUE THREAD

**Issue by wuxiaopei0509** [petitmingchang/TO-GCN#10]
Hello, 
I have only single Time-series data, that is I only have one condition, I find that there is Single_Time-series_data analysis program in the retrive, however there are no instructions about how to run this program，can you update the readme file ?
Thank you very much!

**Comment by papelypluma** [comment]
Hi @wuxiaopei0509. I was wondering if you were able to find a way to do this one? Thanks!

**Comment by petitmingchang** [comment]
Hi @wuxiaopei0509 and @papelypluma 

I just updated the program with single time-series data.
Please try [https://github.com/petitmingchang/TO-GCN_STAR-Protocol](https://github.com/petitmingchang/TO-GCN_STAR-Protocol), thanks!

petitmingchang
