### ISSUE TITLE
Cutoff program failed (Segmentation fault      (core dumped))

### ISSUE THREAD

**Issue by huangziyan11111** [petitmingchang/TO-GCN#11]
I refered this solution to put the input and program Cutoff into same local path, but it still failed without any error. Could you help me? these are the input file, I want to analysis all genes, so the third and fourth expression matrix are the same. [https://github.com/petitmingchang/TO-GCN/issues/7](url)
./Cutoff 4 4 genes.matrix genes.matrix &>Cutoff.log
[genes.matrix.txt](https://github.com/petitmingchang/TO-GCN/files/5877884/genes.matrix.txt)

**Comment by xiuru** [comment]
Hi @huangziyan11111. I was wondering if you were able to figure this out? Thanks!

**Comment by petitmingchang** [comment]
@huangziyan11111 

Since there are 72,389 genes in the genes.matrix.txt, the Cutoff program has to process more than 5 billion correlation values which exceed the limitation. However, the GCN or TO-GCN programs still work for this gene matrix.

petitmingchang
