### ISSUE TITLE
How to visualize in TO-GCN in cytoscape

### ISSUE THREAD

**Issue by nikhilshinde0909** [petitmingchang/TO-GCN#13]
Sir,
I have following output files 
1. C10C2+.csv 
2. TF_levels.csv
I want to visualize time ordered gene co-expression in cytoscape 
How can I ?

**Comment by petitmingchang** [comment]
@nikhilshinde0909 

First, you need to import the C10C2+.csv to the Cytoscape by "File > import > Network from File".
You will get a network now.

Second, you need to import the TF_levels.csv to the Cytoscape by "File > import > Table from File".
and choose import Data as "Node Table Columns".

Third, change the layout by "Layout > Group Attributes Layout > assigned level".
Now, you will get a network arrange by the time order levels.
