### ISSUE TITLE
Can TPM be used as input data?

### ISSUE THREAD

**Issue by Nuturetree** [petitmingchang/TO-GCN#14]
Hello, 
    I wanted to reach out and express my appreciation for your work on To-GCN, a valuable tool for analyzing 3D transcriptomes. I have thoroughly reviewed the methodology outlined in your article, and based on the information provided, I would like to confirm whether TPM (Transcripts Per Million) values can be used as valid input data.
I look forward to your response.
Best regards, Nutures.

**Comment by jordan841220** [comment]
Follow up with this question...in the [paper](https://www.pnas.org/doi/full/10.1073/pnas.1817621116#sec-1) the RPKM values were further underwent upper-quartile normalization before the construction of GCNs. Is this normalization necessary? @petitmingchang

**Comment by petitmingchang** [comment]
@Nuturetree and @JordanCTLin 
Yes, Both "between sample normalized" TPM or FPKM values can be used as input data.
