### ISSUE TITLE
Does TO-GCN support the construction of three conditions?

### ISSUE THREAD

**Issue by zhenqiangfu** [petitmingchang/TO-GCN#15]
Hello, the tools you provided have inspired me a lot, thank you very much. I tried a two-condition network build and it was successful. 
Does TO-GCN support a three-condition build?

**Comment by petitmingchang** [comment]
@zhenqiangfu 
So far the TO-GCN doesn't support three-condition data.
We may extend the method to more than two-condition data in the future.
Thanks!
