### ISSUE TITLE
TFs without any "level in GCN"

### ISSUE THREAD

**Issue by jordan841220** [petitmingchang/TO-GCN#17]
Thank you for developing this interesting tool! 
After toying with it for a week, I have several questions that I failed to find the answers.
In my experiment, there were 2 conditions (control vs. treatment) under 4 timepoints, respectively.

Here are my procedures:
1. cross-sample normalization on raw count matrix using DESeq2
2. then, I did within-sample normalization using TPM
3. `Cutoff 4 4 TF All.genes` to get cutoff values
4. `GCN 4 4 TF TF 0.97 0.95 -0.94 -0.92`
5. focus on C1+C2+.csv: Omit those TFs that belong to a GCN whose size is <10
6. `TO-GCN 4 4 TF TF 0.97 0.95 seeds.txt 0`
7. Visualization

My questions are:
1. Why do I end up with many TFs without any "level in GCN"? (TO-GCN did not assign levels to ALL TFs)
2. Therefore, my plot in cytoscape looks strange with 2 major GCNs (one without any "level in GCN"). Is it normal?
3. In #9 you mentioned that TO-GCN non-comparative version should be used on control-treatment experiment. Do you recommend that I should run TO-GCN_STAR on control and treatment separately?

<img width="554" alt="截圖 2023-12-07 下午4 57 57" src="https://github.com/petitmingchang/TO-GCN/assets/106046583/98ee5848-c6bf-4c4b-b839-d30df10b4ec7">

Thanks.

**Comment by petitmingchang** [comment]
@JordanCTLin
Thanks for using our method in your study. 
First of all, for each condition at least 5 time points were needed to get reliable PCC values for TO-GCN construction.
Here are the response to your questions:
1. Two separated network means there is no any connection between two groups of TFs. You may use looser positive cutoff to make them connect together.
2. The level assignment is initiated from seed TF(s), so you only got one GCN with level assigned. You can input another seed that belongs to the other GCN to get the level assignment for it.
3. Yes, if you want to get two different TO-GCNs you can use the TO-GCN_STAR version.
