### ISSUE TITLE
Process applicable using DESeq2 output (no RPKMs generated)?

### ISSUE THREAD

**Issue by ckeeling** [petitmingchang/TO-GCN#3]
Hello @petitmingchang,

I use DESeq2 for RNAseq analyses, which doesn't generate RPKMs.  In fact, it is oblivious to transcript length in its count-based analysis. Will your analysis be applicable if Variance stabilizing transformed counts are used instead of RPKMs?

[http://bioconductor.org/packages/release/bioc/vignettes/DESeq2/inst/doc/DESeq2.html#variance-stabilizing-transformation](url)

Thanks!

**Comment by petitmingchang** [comment]
Hi @ckeeling,

Thank you for asking!
The gene coexpression relationships are connected by the similarity of expression profiles (expression levels of different time points) between any pair of genes, so you can use either RPKM or VST read counts as expression level to do the TO-GCN analysis.

petitming

**Comment by jordan841220** [comment]
Did anyone try with VST read counts yet? 
It was strange that I got the `Segmentation fault (core dumped)` in Cutoff step only when my inputs were VST read counts.
[All_genes_vst.tsv.zip](https://github.com/petitmingchang/TO-GCN/files/13575549/All_genes_vst.tsv.zip)
[Intersection_TF_vst.tsv.zip](https://github.com/petitmingchang/TO-GCN/files/13575550/Intersection_TF_vst.tsv.zip)

However, when I took the normalized read counts generated from DESeq2 as inputs, everything worked just fine.
[Intersection_TF.tsv.zip](https://github.com/petitmingchang/TO-GCN/files/13575552/Intersection_TF.tsv.zip)
[All_genes.tsv.zip](https://github.com/petitmingchang/TO-GCN/files/13575553/All_genes.tsv.zip)

@petitmingchang  @ckeeling Have you ever encountered this issue?

---

UPDATE: Cutoff using TPM values worked fine, too.
