### ISSUE TITLE
How do you code/order timepoints that have replicates?

### ISSUE THREAD

**Issue by ckeeling** [petitmingchang/TO-GCN#4]
Hello again,
I have 2 conditions at 5 timepoints, with 3 biological replicates/timepoint/condition (30 columns of data).  How do I order or specify this experimental design?  Your examples only indicate the number of samples in the two conditions, not the timepoints or replication.  Thanks!

**Comment by ckeeling** [comment]
Is this possible to do @petitmingchang?

**Comment by petitmingchang** [comment]
Hi ckeeling,

Yes, two options you can try:
1. Use each replicate as an individual sample, so there will be 15 samples for each condition.
2. Use average value of three replicates for each time point, so there will be 5 samples for each condition.
According to my experiences, the 2nd option makes more sense and usually has better result than the first one.

**Comment by ckeeling** [comment]
Thanks @petitmingchang 

So, it is the assumption of the program that the time series is increasing with column left to right, for each condition, and it is categorical and not a continuous scale?  I.e. Days 1, 2, 3 or 1, 5, 100 is not considered?

**Comment by petitmingchang** [comment]
Yes, you are right.

**Comment by ckeeling** [comment]
Thanks
