### ISSUE TITLE
README.md has errors in commands

### ISSUE THREAD

**Issue by ckeeling** [petitmingchang/TO-GCN#5]
### (2) GCN: Constructing eight GCNs for different types

```bash
GCN 13 13 example_data/TFs_1718.tsv example_data/TFs_1718.tsv 0.84 0.84 -0.75 -0.75
```

Should be:

```bash
GCN 13 13 example_data/TFs_1718.tsv example_data/All_genes_25489.tsv 0.83 0.83 -0.76 -0.73
```

### And, (3) TO-GCN: Determining time-ordered level in the interesting GCN

```bash
TO-GCN 13 13 example_data/TFs_1718.tsv example_data/TFs_1718.tsv 0.84 0.84 example_data/seeds.txt 0
```

Should be:
```bash
TO-GCN 13 13 example_data/TFs_1718.tsv example_data/All_genes_25489.tsv 0.84 0.84 example_data/seeds.txt 0
```

**Comment by petitmingchang** [comment]
Thanks for your comment.
For (2) to construction the gene coexpression network (GCN), it depends what relationship you want. If you want to know the coexpression relationship between TF and all genes, you can use the second command you showed. However, if you only want to get the GCN among TFs, please use the original command.
For (3) to determine the time-ordered level of GCN, we should use the original command. Please take a look at the [reference paper](https://doi.org/10.1073/pnas.1817621116) and you will know the reason.
