### ISSUE TITLE
Segmentation fault when running Cutoff program

### ISSUE THREAD

**Issue by mb47** [petitmingchang/TO-GCN#7]
Hi,
I have successfully run Cutoff on the example data, but it segfaults with no further error message when I run my own data through it. I have checked the format of the input data carefully and it appears to be excactly the same as the example data (and it is a smaller dataset). I have six timepoints and two conditions, i.e. 12 columns in addition to the gene IDs. I have attached the input data.
thanks
Micha
[geneLevelTPM.TFs.biorep.1.txt](https://github.com/petitmingchang/TO-GCN/files/4462369/geneLevelTPM.TFs.biorep.1.txt)
[geneLevelTPM.allGenes.biorep.1.txt](https://github.com/petitmingchang/TO-GCN/files/4462370/geneLevelTPM.allGenes.biorep.1.txt)

**Comment by petitmingchang** [comment]
Hi Micha,

I just ran the Cutoff with your data and got the result without any error.

Here is the command and the output:
./Cutoff 6 6 geneLevelTPM.TFs.biorep.1.txt geneLevelTPM.allGenes.biorep.1.txt

No. of TFs: 1057
No. of Genes: 30910
No. of samples under Cond.1: 6
No. of samples under Cond.2: 6

Waiting for histogram generation and cutoff values calculation......

Cutoff of postive coexpression for Cond.1 = 0.92
Cutoff of postive coexpression for Cond.2 = 0.93
Cutoff of negative coexpression for Cond.1 = -0.86
Cutoff of negative coexpression for Cond.2 = -0.85

You can just copy and paste the following command to get the GCNs or change parameters by yourself:
GCN 6 6 geneLevelTPM.TFs.biorep.1.txt geneLevelTPM.allGenes.biorep.1.txt 0.92 0.93 -0.86 -0.85

**Comment by mb47** [comment]
Hi,
thanks for getting back to us. I was trying to point the program at input files located in a different directory (providing absolute paths) but that turned out to be the problem -- apparently the input files need to be co-located with the executables. It worked fine when I ran it with the local files. It would be good to change that, or update the documentation to reflect it.
thanks
Micha

**Comment by wchluo** [comment]
Hi, @petitmingchang 
I got a  same Segmentation fault as @mb47 . The input data carefully checked, and the every Cutoffs contained in "TO-GCN-master" were used except that in "Windows". Could you like to test my input data? 
thanks.
wchluo
![20220328193436](https://user-images.githubusercontent.com/26664986/160391214-fd4f88ed-81e7-4c81-b404-7a160368bff9.png)

[allGene.TPM.txt](https://github.com/petitmingchang/TO-GCN/files/8362328/allGene.TPM.txt)
[TF.TPM.txt](https://github.com/petitmingchang/TO-GCN/files/8362330/TF.TPM.txt)

**Comment by petitmingchang** [comment]
Hi, @wchluo 

I transform your data into "numbers" by excel and the program works.
Please download the attached files and run again.

petitmingchang

[allGene.TPM2.txt](https://github.com/petitmingchang/TO-GCN/files/8367813/allGene.TPM2.txt)
[TF.TPM2.txt](https://github.com/petitmingchang/TO-GCN/files/8367815/TF.TPM2.txt)

**Comment by wchluo** [comment]
Hi, @petitmingchang 

Thank you for you help, the program work good. Then I transform by myselft, works too. Thanks a lot.

wchluo

**Comment by mzhoufulai** [comment]
Hi, @petitmingchang 
I have run  Cutoff with example data successfully, but when i ran my own data,  got segmentation fault error. I tried to transform my data into "numbers" by excel as you mentioned above, but it still failed.  Could you help me to test my input data? Thanks a lot.

Here is my command and output:
./Cutoff 5 5 TF.txt All_genes.txt

No. of TFs: 1380
No. of Genes: 30220
No. of samples under Cond.1: 5
No. of samples under Cond.2: 5

Waiting for histogram generation and cutoff values calculation......

Segmentation fault (core dumped)

Here is my input files:

[All_genes.txt](https://github.com/petitmingchang/TO-GCN/files/8402525/All_genes.txt)
[TF.txt](https://github.com/petitmingchang/TO-GCN/files/8402526/TF.txt)

**Comment by petitmingchang** [comment]
Hi @mzhoufulai 

I found there are some genes whose ID length greater than 25 characters in All_genes.txt. Since TO-GCN programs only accept gene ID length shorter than 21 characters, I just cut down those gene IDs to shorter ones and solved the issue.

petitmingchang

**Comment by Jessica19960620** [comment]
Hi,
I have successfully run Cutoff on the example data, but it segfaults with no further error message when I run my own data through it. I have checked the format of the input data carefully and it appears to be excactly the same as the example data. I have 20 timepoints and two conditions, i.e. 20 columns in addition to the gene IDs. I have attached the input data.
thanks
Jessica
[All_genes.txt](https://github.com/petitmingchang/TO-GCN/files/12002414/All_genes.txt)
[TFs.txt](https://github.com/petitmingchang/TO-GCN/files/12002417/TFs.txt)

**Comment by petitmingchang** [comment]
Hi @Jessica19960620 

I just ran the Cutoff and GCN with your data and found no error.
Here are two commands I used:

`./Cutoff 10 10 TFs.txt All_genes.txt`
`./GCN 10 10 TFs.txt All_genes.txt 0.85 0.85 -0.76 -0.69`

Can you describe your question more clearly? Thanks!

petitmingchang

**Comment by Jessica19960620** [comment]
Hi, petitmingchang

thank you so much. 

Jessica

**Comment by Jessica19960620** [comment]
Hi,
I have two question. 
The first one: I want to calculate the level about C1+C20, but I'm not sure which number can I chose from here(0.91 0.92 -0.95 -0.79).
./TO-GCN 10 10 TO-GCN-S4-10/TF.txt TO-GCN-S4-10/TF.txt 0.91 -0.79 TO-GCN-S4-10/seeds.txt 1
The second: can I use key genes on a biosynthesis pathway as “TF.txt” for TO-GCN?
Thank you so much.
Jessica

**Comment by petitmingchang** [comment]
Hi @Jessica19960620 

For Q1, Please use the command below:

`./TO-GCN 10 10 TO-GCN-S4-10/TF.txt TO-GCN-S4-10/TF.txt 0.91 0.92 TO-GCN-S4-10/seeds.txt 1`

For Q2, I suggest using the original TF.txt because that provides the complete information of time order in the TO-GCN.
Then you can pinpoint which level those key genes locate in the TO-GCN.

petitmingchang

**Comment by Jessica19960620** [comment]
okay. I got it.
Thank you so much.

Jessica
