### ISSUE TITLE
Is TO-GCN suitable for control-treatment type data?

### ISSUE THREAD

**Issue by xiaoyezao** [petitmingchang/TO-GCN#9]
Hi TO-GCN developers,

I have transcriptome data generated from the control-treatment experiment, namely: one sample under control condition, five samples under treatment (for 1h, 2h, 4h, 12h, and 24h respectively) condition.  Does it make sense to analyze these data using TO-GCN?

Bests,

Tao

**Comment by petitmingchang** [comment]
Hi,

Yes, for time-series control treatment type data, please use TO-GCN non-comparative version:
https://github.com/petitmingchang/TO-GCN_STAR-Protocol

petitming
